version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      - mv target/hello.war hello.war
artifacts:
  files:
    - hello.war
    - .ebextensions/**/*